export const ADD_TO_BASKET ='ADD_PRODUCT';
export const GET_NUMBER_INCART ='ADD_TO_CART';
export const SET_PRODUCT ='SET_PRODUCT';
export const SELECTED_PRODUCT ='SELECTED_PRODUCT';
export const REMOVE_SELECTED_PRODUCT ='REMOVE_SELECTED_PRODUCT';
export const FETCH_PRODUCTS="FETCH_PRODUCTS";
